apiVersion: v1
kind: Service
metadata:
  name: my-app-lb
spec:
  type: LoadBalancer
  selector:
    run: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: my-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: my-app
    spec:
      containers:
        - image: jsj6121/bg:1.0
          name: my-app
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: SPRING_DATASOURCE_MASTER_URL
              value: "jdbc:mysql://mysql-service:3306/bettingGround"
            - name: SPRING_DATASOURCE_MASTER_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_MASTER_PASSWORD
              value: "1234"
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
status: {}
