apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - mysql.yaml
  - redis.yaml
#configMapGenerator:
#  - name: init-db
#    files:
#      - configs/init.sql
