apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - mysql.yaml
  - redis.yaml
  - scheduler.yaml
configMapGenerator:
  - name: init-db
    files:
      - configs/init.sql
